Update API version.
For Kubernetes version 1.25.6, I encountered following error with Helm3 and hence need an update. 

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
helm.go:81: [debug] unable to recognize "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
unable to build kubernetes objects from release manifest